In [1]:
import numpy as np

## 1D

In [2]:
NP1 = np.array([1,2,3,4,5,6])

In [3]:
type(NP1)

numpy.ndarray

## 2D

In [4]:
NP2 = np.array([[1,2,3],[4,5,6]])

In [5]:
NP2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(NP2)

numpy.ndarray

In [8]:
# has 2 rows and 3 columns (2,3)
NP2.shape

(2, 3)

In [10]:
# multiply 2 x 3
NP2.size

6

To check the dimension of an array

In [13]:
NP2.ndim


2

In [14]:
NP1.ndim

1

Checks index 

In [16]:
# first element
NP1[0]

1

In [17]:
#third element
NP1[2]

3

Filtering out 1D arrays

In [19]:
NP1[3:5]

array([4, 5])

In [20]:
NP2

array([[1, 2, 3],
       [4, 5, 6]])

2D array
[ROW , COLUMN]

First element of 2D array is the whole row
NP2[0] = [1,2,3]

In [24]:
NP2[0,2]

3

Get the value of the first column

In [25]:
NP2[:,0]

array([1, 4])

In [27]:
# Even NP2[0] would give you the first row
NP2[0,:]

array([1, 2, 3])

In [28]:
# Second row , second column
NP2[1,1]

5

In [30]:
# Even just NP2 would give the same output
NP2[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# First , second rows and skip first column and get second and third columns
NP2[:,1:3]

array([[2, 3],
       [5, 6]])

In [33]:
 NP3 = np.array([[1,2],[3,4]])
 NP4 = np.array([[5,6],[7,8]])
print(NP3)
print(NP4)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [35]:
# Addition will be done element wise
NP3+NP4

array([[ 6,  8],
       [10, 12]])

In [36]:
NP3 - NP4

array([[-4, -4],
       [-4, -4]])

In [37]:
NP3/NP4

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [39]:
NP3*NP4

array([[ 5, 12],
       [21, 32]])

In [40]:
#matrix multiplication format
NP3@NP4

array([[19, 22],
       [43, 50]])